title: Cameron Barrett
theme: minima

minima:
  skin: solarized-light
  
github_username: cameron-barrett
 
author: "Cameron Barrett"

header_pages:
  - index.md
  - commonplace.md
  - thoughts.md
  - media.md
